sudo: required
services:
  - docker

before_install:
  - docker build -t negi007/docker-react -f Dockerfile.dev .


script:
  - docker run negi007/docker-react npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "Docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-877188100509"
  bucket_path: "Docker-react"
  on:
    branch: master
  access_key_id: $aws_access_key
  secret_access_key: 
    secure: "$aws_secret_key"